/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#ebdcff",
        "surface-container-high": "#2a2a2a",
        "on-tertiary": "#36265e",
        "inverse-on-surface": "#313030",
        "on-secondary-fixed": "#001a40",
        "tertiary-fixed": "#e9ddff",
        "inverse-primary": "#723cce",
        "on-secondary": "#002f67",
        "inverse-surface": "#e5e2e1",
        "on-error": "#690005",
        "on-primary-fixed-variant": "#591bb5",
        "tertiary-container": "#7969a5",
        "on-tertiary-container": "#fdf7ff",
        "primary": "#d3bbff",
        "primary-fixed-dim": "#d3bbff",
        "on-primary-container": "#fdf6ff",
        "on-secondary-container": "#f8f8ff",
        "on-surface": "#e5e2e1",
        "on-background": "#e5e2e1",
        "surface-dim": "#131313",
        "on-primary-fixed": "#260059",
        "surface": "#131313",
        "secondary": "#acc7ff",
        "secondary-fixed": "#d7e2ff",
        "surface-tint": "#d3bbff",
        "surface-bright": "#393939",
        "on-secondary-fixed-variant": "#004591",
        "secondary-container": "#046fe1",
        "error": "#ffb4ab",
        "on-primary": "#40008d",
        "surface-container": "#201f1f",
        "on-error-container": "#ffdad6",
        "background": "#131313",
        "outline": "#948ea1",
        "surface-container-highest": "#353534",
        "surface-container-lowest": "#0e0e0e",
        "secondary-fixed-dim": "#acc7ff",
        "outline-variant": "#494455",
        "on-tertiary-fixed-variant": "#4d3d76",
        "primary-container": "#8753e3",
        "on-surface-variant": "#cac3d8",
        "error-container": "#93000a",
        "surface-variant": "#353534",
        "surface-container-low": "#1c1b1b",
        "tertiary": "#cfbcff",
        "on-tertiary-fixed": "#210f48",
        "tertiary-fixed-dim": "#cfbcff"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [],
}
